[package]
name = "actix-front-end"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.6.0-beta.1"
serde_json = "1.0.113"
serde = { version = "1.0.130", features = ["derive"] }
futures = "0.3.17"
actix-files = "0.6.0"
